### ISSUE TITLE
Extruding along a closed path does not close the result object

### ISSUE THREAD

**Issue by tnakagome** [nolanyee/blender-path-extrude#1]
Hi. Thanks for a great tool. It works well for an open-ended path/wire.

On the other hand, when I execute it against a closed path/wire, it creates a gap between the last element and the first element of the vertex array. I have been trying to close the gap myself but the two surfaces at the beginning and the end do not fit perfectly.

It would be great if the code can support a closed path.

Thanks.

**Comment by nolanyee** [comment]
Version 2.0 has been released, with support for closed loops, as well as fixing a couple of other minor issues.

**Comment by tnakagome** [comment]
Thank you. The new version works perfectly.
