### ISSUE TITLE
Extrusion stops in the middle

### ISSUE THREAD

**Issue by tnakagome** [nolanyee/blender-path-extrude#5]
Hello again!

This time extrusion stops in the middle.

<img width="531" alt="Screenshot 2021-02-11 17 58 14" src="https://user-images.githubusercontent.com/19327519/107617248-e3ee4380-6c92-11eb-8c30-82fcc3009809.png">

<img width="531" alt="Screenshot 2021-02-11 17 58 34" src="https://user-images.githubusercontent.com/19327519/107617264-ec467e80-6c92-11eb-9533-2147b39cf147.png">

Not sure if this is helpful, but these are the vertex positions. There are 11 vertices in total.
0: 25.98, 15.00, 0.00
1: 13.54, 11.36, 0.00
2: -13.54, -11.36, 0.00
3: -25.98, -15.00, 0.00
4: -34.89, -12.70, 0.00
5: -40.50, -7.14, 0.00
6: -42.43, -0.00, 0.00
7: -40.50, 7.14, 0.00
8: -34.89, 12.70, 0.00
9: -25.98, 15.00, 0.00
10: -13.54, 11.36, 0.00
As you can see there is no vertex at the origin this time and there is no loop.

Thanks!
[ExtrusionTest3.blend.zip](https://github.com/nolanyee/blender-path-extrude/files/5964022/ExtrusionTest3.blend.zip)

**Comment by nolanyee** [comment]
Good catch. This was due to a division by 0 error. It should be fixed now in version 3.3.

**Comment by tnakagome** [comment]
Great! Thank you. Closing.
