### ISSUE TITLE
math domain error from acos?

### ISSUE THREAD

**Issue by tnakagome** [nolanyee/blender-path-extrude#8]
Hello again. It's been a while.

I am using this library with Blender 4.1 now, and experiencing this error.

Python: Traceback (most recent call last):
  File "C:\PathExtrude.py", line 236, in execute
ValueError: math domain error

It seems to come from acos() in 

`factor_list.append(1/math.sin(math.acos(np.dot(-1*normalized_differences[i],normalized_differences[i+1]))/2))`

This is the .blend that reproduces the problem. It would be great if it can be fixed.

[DomainError.zip](https://github.com/user-attachments/files/16028369/DomainError.zip)

Thank you!

**Comment by nolanyee** [comment]
This was probably due to a floating point error. I modified the code to force the arguments to be within the acos() range. It should work now.

**Comment by tnakagome** [comment]
Great! Thank you very much.
